Lab | Pandas Deep-Dive
1. Import Pandas package under the alias pd and Numpy under the alias np
 
2. Define a variable called path that contains the path to the csv file you downloaded.

In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('apple_store.csv')

In [6]:
data

,id,track_name,size_bytes,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,prime_genre
0,281656475,PAC-MAN Premium,100788224,3.99,21292,26,4.0,4.5,Games
1,281796108,Evernote - stay organized,158578688,0.00,161065,26,4.0,3.5,Productivity
2,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,0.00,188583,2822,3.5,4.5,Weather
3,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,0.00,262241,649,4.0,4.5,Shopping
4,282935706,Bible,92774400,0.00,985920,5320,4.5,5.0,Reference
...,...,...,...,...,...,...,...,...,...
7192,1187617475,Kubik,126644224,0.00,142,75,4.5,4.5,Games
7193,1187682390,VR Roller-Coaster,120760320,0.00,30,30,4.5,4.5,Games
7194,1187779532,Bret Michaels Emojis + Lyric Keyboard,111322112,1.99,15,0,4.5,0.0,Utilities
7195,1187838770,VR Roller Coaster World - Virtual Reality,97235968,0.00,85,32,4.5,4.5,Games
7196,1188375727,Escape the Sweet Shop Series,90898432,0.00,3,3,5.0,5.0,Games

 Print the first 5 rows of data to see what the data look like.
A data analyst usually does this to have a general understanding about what the data look like before digging deep.

 
5. Print the summary (info) of the data.
 
6. Print the number of columns in the data.
 
7. Print all column names.

In [7]:
data.head(5)

,id,track_name,size_bytes,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,prime_genre
0,281656475,PAC-MAN Premium,100788224,3.99,21292,26,4.0,4.5,Games
1,281796108,Evernote - stay organized,158578688,0.00,161065,26,4.0,3.5,Productivity
2,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,0.00,188583,2822,3.5,4.5,Weather
3,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,0.00,262241,649,4.0,4.5,Shopping
4,282935706,Bible,92774400,0.00,985920,5320,4.5,5.0,Reference

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                7197 non-null   int64
 1   track_name        7197 non-null   object
 2   size_bytes        7197 non-null   int64
 3   price             7197 non-null   float64
 4   rating_count_tot  7197 non-null   int64
 5   rating_count_ver  7197 non-null   int64
 6   user_rating       7197 non-null   float64
 7   user_rating_ver   7197 non-null   float64
 8   prime_genre       7197 non-null   object
dtypes: float64(3), int64(4), object(2)
memory usage: 506.2+ KB

In [13]:
len(data.columns)

9

In [17]:
data.columns

Index(['id', 'track_name', 'size_bytes', 'price', 'rating_count_tot',
       'rating_count_ver', 'user_rating', 'user_rating_ver', 'prime_genre'],
      dtype='object')

Now that we have a general understanding of the data, we'll start working on the challenge questions.

How many apps are there in the data source? Print the # of observations of the data.
Hint: Your code should return the number 7197.

In [18]:
data.value_counts('id')

id
281656475     1
1058526204    1
1061661355    1
1061610336    1
1061572575    1
             ..
785638228     1
785537179     1
785267899     1
784797900     1
1188375727    1
Length: 7197, dtype: int64

9. What is the average rating of all apps?
First, read the user_rating column into a varialbe named user_rating.

In [21]:
userrating= data['user_rating']

In [22]:
userrating.mean()

3.526955675976101

How many apps have an average rating no less than 4?
First, filter user_rating where its value >= 4.

Assign the filtered dataframe to a new variable called user_rating_high.

In [23]:
user_rating_4 = data[userrating >= 4]

In [24]:
user_rating_4

,id,track_name,size_bytes,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,prime_genre
0,281656475,PAC-MAN Premium,100788224,3.99,21292,26,4.0,4.5,Games
1,281796108,Evernote - stay organized,158578688,0.00,161065,26,4.0,3.5,Productivity
3,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,0.00,262241,649,4.0,4.5,Shopping
4,282935706,Bible,92774400,0.00,985920,5320,4.5,5.0,Reference
5,283619399,Shanghai Mahjong,10485713,0.99,8253,5516,4.0,4.0,Games
...,...,...,...,...,...,...,...,...,...
7192,1187617475,Kubik,126644224,0.00,142,75,4.5,4.5,Games
7193,1187682390,VR Roller-Coaster,120760320,0.00,30,30,4.5,4.5,Games
7194,1187779532,Bret Michaels Emojis + Lyric Keyboard,111322112,1.99,15,0,4.5,0.0,Utilities
7195,1187838770,VR Roller Coaster World - Virtual Reality,97235968,0.00,85,32,4.5,4.5,Games
7196,1188375727,Escape the Sweet Shop Series,90898432,0.00,3,3,5.0,5.0,Games

Now obtain the length of user_rating_high which should return 4781.

In [25]:
len(user_rating_4.value_counts())

4781

How many genres are there in total for all the apps?
Define a new variable named genres that contains the prime_genre column of data. Google for how to obtain unique values of a dataframe column.

In [26]:
genres=data['prime_genre'].unique()

In [27]:
genres

array(['Games', 'Productivity', 'Weather', 'Shopping', 'Reference',
       'Finance', 'Music', 'Utilities', 'Travel', 'Social Networking',
       'Sports', 'Business', 'Health & Fitness', 'Entertainment',
       'Photo & Video', 'Navigation', 'Education', 'Lifestyle',
       'Food & Drink', 'News', 'Book', 'Medical', 'Catalogs'],
      dtype=object)

In [28]:
len(genres)

23

What are the top 3 genres that have the most number of apps?
What you want to do is to count the number of occurrences of each unique genre values. Because you already know how to obtain the unique genre values, you can of course count the # of apps of each genre one by one. However, Pandas has a convinient function to let you count all values of a dataframe column with a single command. Google for "pandas count values" to find the solution.

In [32]:
data['prime_genre'].value_counts()[:3]

Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64

Which genre is most likely to contain free apps?
First, filter data where the price is 0.00. Assign the filtered data to a new variable called free_apps. Then count the values in free_apps

In [33]:
free_apps = data[data['price'] == 0]

In [34]:
free_apps

,id,track_name,size_bytes,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,prime_genre
1,281796108,Evernote - stay organized,158578688,0.0,161065,26,4.0,3.5,Productivity
2,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,0.0,188583,2822,3.5,4.5,Weather
3,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,0.0,262241,649,4.0,4.5,Shopping
4,282935706,Bible,92774400,0.0,985920,5320,4.5,5.0,Reference
6,283646709,PayPal - Send and request money safely,227795968,0.0,119487,879,4.0,4.5,Finance
...,...,...,...,...,...,...,...,...,...
7188,1186384912,Demolition Derby Virtual Reality (VR) Racing,168774656,0.0,18,18,4.0,4.0,Games
7192,1187617475,Kubik,126644224,0.0,142,75,4.5,4.5,Games
7193,1187682390,VR Roller-Coaster,120760320,0.0,30,30,4.5,4.5,Games
7195,1187838770,VR Roller Coaster World - Virtual Reality,97235968,0.0,85,32,4.5,4.5,Games
7196,1188375727,Escape the Sweet Shop Series,90898432,0.0,3,3,5.0,5.0,Games

In [36]:
len(free_apps.value_counts())

4056

In [38]:
free_apps['prime_genre'].value_counts()

Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Business               20
Reference              20
Navigation             20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64

Now you can calculate the proportion of the free apps in each genre based on the value counts you obtained in the previous two steps.

In [44]:
proportion=(free_apps['prime_genre'].value_counts())/(data['prime_genre'].value_counts())

In [45]:
proportion

Book                 0.589286
Business             0.350877
Catalogs             0.900000
Education            0.291391
Entertainment        0.624299
Finance              0.807692
Food & Drink         0.682540
Games                0.584412
Health & Fitness     0.422222
Lifestyle            0.652778
Medical              0.347826
Music                0.485507
Navigation           0.434783
News                 0.773333
Photo & Video        0.478510
Productivity         0.348315
Reference            0.312500
Shopping             0.991803
Social Networking    0.856287
Sports               0.692982
Travel               0.691358
Utilities            0.439516
Weather              0.430556
Name: prime_genre, dtype: float64

If a developer tries to make money by developing and selling Apple Store apps, in which genre should s/he develop the apps? Please assume all apps cost the same amount of time and expense to develop.
We will leave this question to you. There are several ways to solve it.

In [46]:

avg_price = data.groupby('prime_genre').mean().sort_values('price', ascending=False)['price'].reset_index()
avg_price.rename(columns={'price':'avg_price', 'prime_genre': 'genre'}).set_index('genre')

                   avg_price
genre
Medical             8.776087
Business            5.116316
Reference           4.836875
Music               4.835435
Productivity        4.330562
Navigation          4.124783
Education           4.028234
Health & Fitness    1.916444
Book                1.790536
Utilities           1.647621
Weather             1.605417
Food & Drink        1.552381
Photo & Video       1.473295
Games               1.432923
Travel              1.120370
Sports              0.953070
Entertainment       0.889701
Lifestyle           0.885417
Catalogs            0.799000
News                0.517733
Finance             0.421154
Social Networking   0.339880
Shopping            0.016311